version: '2'
services:
  web:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://developer@postgres/haufe
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: developer
      POSTGRES_DB: haufe
  client:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./src:/usr/share/nginx/html