version: '3.7'
services:
  api:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app/
      - /node_modules
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      POSTGRES_USER: developer
      POSTGRES_HOST: localhost
      POSTGRES_DB: developer
      POSTGRES_PORT: 5432
    network_mode:
      host
  client:
    build: ./client
    volumes:
      - ./client:/app
  postgres:
    image: postgres:9.6.2-alpine
    environment:
      POSTGRES_USER: developer
      POSTGRES_PORT: 5432
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    network_mode:
      host
  pgAdmin:
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin@domain.com
      - PGADMIN_DEFAULT_PASSWORD=password
      - PGADMIN_LISTEN_PORT=5050
    volumes:
      - pga4volume:/var/lib/pgadmin
    network_mode:
      host
    depends_on:
      - postgres
  nginx:
    image: nginx
    ports:
      - 8000:80
    depends_on:
      - client
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro

volumes:
  pga4volume:
    name: pga4volume_data