POST http://localhost:3000/api/users/external/create?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIxd3dpejJlazZ6Nm0wZGQiLCJ1c2VybmFtZSI6ImludGVybmFsIiwicm9sZSI6ImludGVybmFsIiwiaWF0IjoxNTgyNDgxNjUwLCJleHAiOjE1ODI0ODUyNTB9.kTDL7XFI0GhA3fRHeVA_RudwqtUENlcgIdynqNUPFCE
Content-Type: application/json

{
  "email": "testExternal@gmail.com",
  "username": "externalUser",
  "password": "password"
}

###
