DELETE http://localhost:3000/api/users/external/delete?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI1czY4djNmazZ6Zmp2MnYiLCJ1c2VybmFtZSI6ImpvaG4iLCJyb2xlIjoiaW50ZXJuYWwiLCJpbWdTb3VyY2UiOiJodHRwczovL2luc3RhZ3JhbS5mdHNyMS0xLmZuYS5mYmNkbi5uZXQvdi90NTEuMjg4NS0xNS9zaDAuMDgvZTM1L2MwLjE4MC4xNDQwLjE0NDBhL3M2NDB4NjQwLzg3MjQyMzgyXzM1MTU1MDk0NTUxOTA0NjNfODYzMDkwNTE1NTQwNTUyOTMyN19uLmpwZz9fbmNfaHQ9aW5zdGFncmFtLmZ0c3IxLTEuZm5hLmZiY2RuLm5ldCZfbmNfY2F0PTExMSZfbmNfb2hjPXFrQnlrcTV2Q1J3QVgtSzMwNl8mb2g9YTMwYWE0NmM3NjNlZjljZjhlNTc1Y2Y5MGNjZDE2OTcmb2U9NUU4NUNBMDQiLCJpYXQiOjE1ODI0ODc1NjYsImV4cCI6MTU4MjQ5MTE2Nn0.MaqmL8Fleq_18f_gSWYdCPKuGCJ7FjhJFj0uuvuQs6w&userId=5s68v9ek6zg9n6w
Content-Type: application/json

###
